### PR TITLE
shorter alternatives and a little refactor

### PR DESCRIPTION
**Pull request by danimateo**

### CODE REVIEW

**Comment by RyanGreenup** [comment]
Sorry for the late reply, I thought *GitHub* would notify me of PR's, I didn't realise I had to watch my own repo :rofl:.

~~Do you think we should have shorter commands or do you think we should just leave it to the user to implement aliases?~~

Oh I see the `|` is or, I overlooked that, unfourtunately the branches have diverged so I'll have to go through and do that now.

I'm happy either way, but that's why I left the names long and descriptive, e.g.:

    alias np='cadmus  preview'

**Comment by RyanGreenup** [comment]
How should we implement the help :thinking:, maybe bold only the first matching letter?

        echo -e " 🔍 \e[1;93m \e[1mf\e[0m\e[93mind \e[0m \e[1;34m    ┊┊┊ 🎆 \e[0m Find Notes based on FileName"

image

**Comment by danimateo** [comment]
Yeah, that looks great!

**Comment by RyanGreenup** [comment]
Alright thanks heaps, I'll merge in those changes and I'll make an issue on emboldening the shortcut keys in case I forget to do that

**Pull request merged**
